### PR TITLE
Code improvements

### PR DESCRIPTION
**Pull request by SimplyCEO**
More automated script with less system barriers.

### CODE REVIEW

**Comment by LilithRainbows** [comment]
Been busy with other things, i will check it this week, thank you 💕

**Comment by SimplyCEO** [comment]
Sorry for not putting this in a 'patch' branch. I'm dumb lol

**Comment by LilithRainbows** [comment]
> Sorry for not putting this in a 'patch' branch. I'm dumb lol

No, it's fine, sorry for taking so long, this week I promise to review everything 🤭
You are so kind 💕

**Comment by SimplyCEO** [comment]
Hold the request. I'm updating the script.
It has features for Debian-only, which makes quite difficult to detect any bug in other distributions.

I'm also providing error messages in case the installation don't get successful, which by looking at the script it basically doesn't care if the packages are installed or not lol

**Comment by SimplyCEO** [comment]
Works flawlessly, but the xterm assumes that the current distribution uses `dpkg`.
Shouldn't be a problem, since I could log-in.

**Comment by alinpr18** [comment]
You should remove xterm as a dependency, there's no need for a terminal when you already know you'll run that command from a terminal

```
if type dpkg &>/dev/null; then
    packages='tar unzip wget libnss3'
else
    packages='tar unzip wget nss'
fi
```

I am testing the script of your branch but the game never starts, it is in an eternal loop of 60% I only managed to enter the first start

### System info

Linux Mint 20.3 Cinnamon
5.4.0-122-generic

**Comment by SimplyCEO** [comment]
> You should remove xterm as a dependency, there's no need for a terminal when you already know you'll run that command from a terminal
> 
> ```
> if type dpkg &>/dev/null; then
>     packages='tar unzip wget libnss3'
> else
>     packages='tar unzip wget nss'
> fi
> ```

XTerm is needed since the `HabboAirForLinux.desktop` file has the `Terminal` value enabled.
If XTerm is not installed, it will simply not run when the menu launch is used.

**Comment by SimplyCEO** [comment]
> it is in an eternal loop of 60%

What do you mean? Could you provide a log in the [issues](https://github.com/KanuX-14/HabboAirForLinux/issues) tab?

**Comment by alinpr18** [comment]
> > You should remove xterm as a dependency, there's no need for a terminal when you already know you'll run that command from a terminal
> > ```
> > if type dpkg &>/dev/null; then
> >     packages='tar unzip wget libnss3'
> > else
> >     packages='tar unzip wget nss'
> > fi
> > ```
> 
> XTerm is needed since the `HabboAirForLinux.desktop` file has the `Terminal` value enabled. If XTerm is not installed, it will simply not run when the menu launch is used.

It is that when running HabboLauncher.desktop it automatically opens the terminal of the installed distribution. In my case gnome-terminal

> > it is in an eternal loop of 60%
> 
> What do you mean? Could you provide a log in the [issues](https://github.com/KanuX-14/HabboAirForLinux/issues) tab?

I try to see what problem the terminal reports to me but it does not host anything, it just stays in a loading loop at 60%, right now it loaded me but it takes a while

**Comment by SimplyCEO** [comment]
> It is that when running HabboLauncher.desktop it automatically opens the terminal of the installed distribution.

Some distributions have more than one desktop option to choose. Some of them already set the default terminal emulator, some not.<br>
It is just a compatibility thing. I may add a option to ignore this package.

> right now it loaded me but it takes a while

Generally it could be the Habbo host or your internet, if you are talking about the in-game loading bar.

**Comment by alinpr18** [comment]
> Generally it could be the Habbo host or your internet, if you are talking about the in-game loading bar.

I have come to the conclusion that it is the Habbo host or something is wrong. My internet is very good and currently I checked and the ping is excellent. At least this script runs the game better, I have the game also running with Bottles and there when loading a heavy room it gets corrupted.

**Pull request merged**
